namespace GameServerCore.Enums
{
    public enum AIState : uint
    {
        AI_IDLE = 0,
        AI_SOFTATTACK = 1,
        AI_HARDATTACK = 2,
        AI_ATTACKMOVESTATE = 3,
        AI_STANDING = 4,
        AI_MOVE = 5,
        AI_GUARD = 6,
        AI_ATTACK = 7,
        AI_RETREAT = 8,
        AI_HARDIDLE = 9,
        AI_HARDIDLE_ATTACKING = 10,
        AI_TAUNTED = 11,
        AI_ATTACKMOVE_ATTACKING = 12,
        AI_FEARED = 13,
        AI_CHARMED = 14,
        AI_FLEEING = 15,
        AI_ATTACK_GOING_TO_LAST_KNOWN_LOCATION = 16,
        AI_HALTED = 17,
        AI_SIEGEATTACK = 18,
        AI_LAST_NONPET_AI_STATE = 19,
        AI_ATTACK_HERO,
        AI_FOLLOW,
        AI_FOLLOW_HERO,
        AI_PET_ATTACK, // 20?
        AI_PET_ATTACKMOVE,
        AI_PET_ATTACKMOVE_ATTACKING,
        AI_PET_HARDATTACK,
        AI_PET_HARDIDLE,
        AI_PET_HARDIDLE_ATTACKING,
        AI_PET_HARDMOVE,
        AI_PET_HARDRETURN,
        AI_PET_HARDSTOP,
        AI_PET_HOLDPOSITION,
        AI_PET_HOLDPOSITION_ATTACKING,
        AI_PET_IDLE,
        AI_PET_MOVE,
        AI_PET_RETURN,
        AI_PET_RETURN_ATTACKING,
        AI_PET_SPAWNING,
        AI_SHOP,
        AI_STOP,
    }
}
